package v1

import "github.com/slsa-framework/slsa-verifier/v2/verifiers/internal/gha/slsaprovenance/iface"

// ContainerBasedBuildType is the build type for the container-based builder.
var ContainerBasedBuildType = "https://slsa.dev/container-based-build/v0.1?draft"

// ContainerBasedProvenance is provenance generated by the container-based builder.
type ContainerBasedProvenance struct {
	*provenanceV1
}

func newContainerBased(a *Attestation) iface.Provenance {
	return &ContainerBasedProvenance{
		provenanceV1: &provenanceV1{
			prov: a,
		},
	}
}
