package v1

// ContainerBasedBuildType is the build type for the container-based builder.
var ContainerBasedBuildType = "https://slsa.dev/container-based-build/v0.1?draft"

// ContainerBasedProvenance is provenance generated by the container-based builder.
type ContainerBasedProvenance struct {
	*provenanceV1
}
