package v1

// containerBasedBuildType is the build type for the container-based builder and is based on BYOB.
var containerBasedBuildType = "https://slsa.dev/container-based-build/v0.1?draft"

// ContainerBasedProvenance is provenance generated by the container-based builder.
type ContainerBasedProvenance struct {
	// NOTE: The Container-based builder is not based on BYOB framework but the
	// provenanece is identical and can be treated the same (for now).
	*BYOBProvenance
}
