package v1

import (
	"fmt"

	serrors "github.com/slsa-framework/slsa-verifier/v2/errors"
)

// GithubAttestBuildType is the build type for the github attest based builder.
var GithubAttestBuildType = "https://actions.github.io/buildtypes/workflow/v1"

// GithubAttestProvenance is provenance generated by an action using github's attest action.
type GithubAttestProvenance struct {
	*provenanceV1
}

func (p *GithubAttestProvenance) TriggerURI() (string, error) {
	externalParams, err := p.getExternalParameters()
	if err != nil {
		return "", err
	}
	workflow, ok := externalParams["workflow"].(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("%w: %s", serrors.ErrorInvalidFormat, "workflow parameters")
	}
	repository, ok := workflow["repository"].(string)
	if !ok {
		return "", fmt.Errorf("%w: %s", serrors.ErrorInvalidFormat, "workflow parameters: repository")
	}
	ref, ok := workflow["ref"].(string)
	if !ok {
		return "", fmt.Errorf("%w: %s", serrors.ErrorInvalidFormat, "workflow parameters: ref")
	}
	uri := fmt.Sprintf("git+%s@%s", repository, ref)
	return uri, nil
}
